export const PREVIEW_JOBS = {
  searchSources: {
    ready: true,
    searches: { enabled: 4, total: 5 },
    trackedCompanies: 12,
    deterministicSources: { attempted: 16, rss: 4, supportedAtsCompanies: 12, skipped: 0 },
  },
  sourcing: {
    manualSearchRun: {
      purpose: "manual-search",
      status: "idle",
      summary: "Last sweep added 6 roles and left 4 for review.",
    },
  },
  jobs: {
    visibleCount: 11,
    rail: {
      screenPlus: 4,
      fresh: 5,
      highFit: 6,
      manualReview: 4,
      terminal: 1,
      nextDecision: {
        title: "Review 4 sourced roles",
        summary: "Promote, skip, or park the highest-fit roles before adding more work.",
        action: "manual-review",
        hasWork: true,
      },
    },
    funnel: [
      { id: "applied", label: "Applied", count: 2, color: "#F2C94C" },
      { id: "screen", label: "Screen", count: 2, color: "#5DADEC" },
      { id: "technical", label: "Technical", count: 1, color: "#2F9E8F" },
      { id: "hiring-manager", label: "Hiring Manager", count: 1, color: "#E8553D" },
      { id: "rejected", label: "Rejected", count: 1, color: "#8E8B84" },
    ],
    sankey: {
      total: 7,
      nodes: [
        {
          id: "src-cold",
          label: "Cold",
          color: "#8E8B84",
          count: 3,
          col: 0,
          order: 0,
          filter: "src-cold",
        },
        {
          id: "src-recruiter",
          label: "Recruiter",
          color: "#5DADEC",
          count: 2,
          col: 0,
          order: 1,
          filter: "src-recruiter",
        },
        {
          id: "src-referral",
          label: "Referral",
          color: "#2F9E8F",
          count: 2,
          col: 0,
          order: 2,
          filter: "src-referral",
        },
        {
          id: "awaiting",
          label: "Awaiting",
          color: "#F2C94C",
          count: 2,
          col: 1,
          order: 0,
          filter: "awaiting",
        },
        {
          id: "heardback",
          label: "Heard back",
          color: "#5DADEC",
          count: 5,
          col: 1,
          order: 1,
          filter: "heardback",
        },
        {
          id: "stale",
          label: "Going stale",
          color: "#C9942E",
          count: 1,
          col: 1.5,
          order: 1.5,
          filter: "stale",
        },
        {
          id: "screen",
          label: "Screen",
          color: "#5DADEC",
          count: 3,
          col: 2,
          order: 0,
          filter: "reached-screen",
        },
        {
          id: "technical",
          label: "Technical",
          color: "#2F9E8F",
          count: 1,
          col: 3,
          order: 0,
          filter: "reached-technical",
        },
        {
          id: "hiring-manager",
          label: "Hiring manager",
          color: "#E8553D",
          count: 1,
          col: 4,
          order: 0,
          filter: "reached-hiring-manager",
        },
        {
          id: "rejected",
          label: "Rejected",
          color: "#8E8B84",
          count: 1,
          col: 2.5,
          order: 0,
          filter: "terminal",
        },
      ],
      links: [
        {
          from: "src-cold",
          to: "awaiting",
          count: 2,
          color: "#F2C94C",
          examples: ["Northstar Systems", "Helio Grid"],
          filter: "awaiting",
        },
        {
          from: "src-cold",
          to: "heardback",
          count: 1,
          color: "#5DADEC",
          examples: ["Closed Door"],
          filter: "heardback",
        },
        {
          from: "src-recruiter",
          to: "heardback",
          count: 2,
          color: "#5DADEC",
          examples: ["Signal Harbor", "Atlas Forge"],
          filter: "heardback",
        },
        {
          from: "src-referral",
          to: "heardback",
          count: 2,
          color: "#2F9E8F",
          examples: ["Vector Loom", "Pinnacle Data"],
          filter: "heardback",
        },
        {
          from: "awaiting",
          to: "stale",
          count: 1,
          color: "#C9942E",
          examples: ["Helio Grid"],
          filter: "stale",
        },
        {
          from: "heardback",
          to: "screen",
          count: 3,
          color: "#5DADEC",
          examples: ["Signal Harbor", "Atlas Forge", "Closed Door"],
          filter: "reached-screen",
        },
        {
          from: "heardback",
          to: "technical",
          count: 1,
          color: "#2F9E8F",
          examples: ["Vector Loom"],
          filter: "reached-technical",
        },
        {
          from: "heardback",
          to: "hiring-manager",
          count: 1,
          color: "#E8553D",
          examples: ["Pinnacle Data"],
          filter: "reached-hiring-manager",
        },
        {
          from: "screen",
          to: "rejected",
          count: 1,
          color: "#8E8B84",
          examples: ["Closed Door"],
          filter: "terminal",
        },
      ],
    },
    rows: [
      {
        id: "preview-northstar",
        source: "application",
        company: "Northstar Systems",
        role: "Applied AI Engineer",
        domain: "northstar.example",
        location: "New York hybrid",
        comp: "$225k-$255k",
        compSummary: "$225k-$255k base",
        stage: "applied",
        sankeyStage: "applied",
        stageLabel: "Applied",
        sourceBucket: "src-cold",
        channel: "board",
        mode: "hybrid",
        appliedAt: "2026-07-02",
        appliedLabel: "Jul 2",
        fit: 87,
        fitBasis: "screened",
        baseK: 225,
        compMidpointK: 240,
        terminal: false,
        roundsReached: 0,
        needsReview: false,
        needsAction: false,
        stale: false,
        ghosted: false,
        missingComp: false,
        highFit: true,
        interviewPath: false,
        actionState: "active",
        workstream: "watch",
        action: { cta: "Track", dueText: "Warm" },
        searchText: "northstar systems applied ai engineer new york hybrid board",
      },
      {
        id: "preview-helio",
        source: "application",
        company: "Helio Grid",
        role: "AI Infrastructure Engineer",
        domain: "helio.example",
        location: "Remote US",
        comp: "$210k-$240k",
        compSummary: "$210k-$240k base",
        stage: "applied",
        sankeyStage: "applied",
        stageLabel: "Applied",
        sourceBucket: "src-cold",
        channel: "portal",
        mode: "remote",
        appliedAt: "2026-06-21",
        appliedLabel: "Jun 21",
        fit: 80,
        fitBasis: "screened",
        baseK: 210,
        compMidpointK: 225,
        terminal: false,
        roundsReached: 0,
        needsReview: false,
        needsAction: false,
        stale: true,
        ghosted: false,
        missingComp: false,
        highFit: true,
        interviewPath: false,
        decayState: "stale",
        actionState: "stale",
        workstream: "stale",
        healthBadge: { rating: "watch", label: "Watch", title: "Hiring pace has slowed" },
        action: { cta: "Follow up", dueText: "Today" },
        searchText: "helio grid ai infrastructure engineer remote portal",
      },
      {
        id: "preview-signal",
        source: "application",
        company: "Signal Harbor",
        role: "AI Platform Lead",
        domain: "signal.example",
        location: "Remote",
        comp: "$230k base",
        compSummary: "$230k base",
        stage: "screen",
        sankeyStage: "screen",
        stageLabel: "Screen",
        sourceBucket: "src-recruiter",
        channel: "recruiter",
        mode: "remote",
        appliedAt: "2026-06-28",
        appliedLabel: "Jun 28",
        fit: 84,
        fitBasis: "screened",
        baseK: 230,
        compMidpointK: 230,
        terminal: false,
        roundsReached: 1,
        needsReview: false,
        needsAction: true,
        stale: false,
        ghosted: false,
        missingComp: false,
        highFit: true,
        interviewPath: true,
        actionState: "needs-action",
        workstream: "interview",
        action: { cta: "Prep", dueText: "Tomorrow" },
        searchText: "signal harbor ai platform lead remote recruiter",
      },
      {
        id: "preview-atlas",
        source: "application",
        company: "Atlas Forge",
        role: "Staff ML Systems Engineer",
        domain: "atlas.example",
        location: "Boston hybrid",
        comp: "$220k-$250k",
        compSummary: "$220k-$250k base",
        stage: "screen",
        sankeyStage: "screen",
        stageLabel: "Screen",
        sourceBucket: "src-recruiter",
        channel: "recruiter",
        mode: "hybrid",
        appliedAt: "2026-06-10",
        appliedLabel: "Jun 10",
        fit: 76,
        fitBasis: "screened",
        baseK: 220,
        compMidpointK: 235,
        terminal: false,
        roundsReached: 1,
        needsReview: false,
        needsAction: false,
        stale: false,
        ghosted: true,
        missingComp: false,
        highFit: false,
        interviewPath: true,
        decayState: "ghosted",
        actionState: "ghosted",
        workstream: "ghosted",
        action: { cta: "Revive", dueText: "30d" },
        searchText: "atlas forge staff ml systems engineer boston recruiter",
      },
      {
        id: "preview-vector",
        source: "application",
        company: "Vector Loom",
        role: "Staff AI Engineer",
        domain: "vector.example",
        location: "NYC hybrid",
        comp: "$245k-$280k",
        compSummary: "$245k-$280k base",
        stage: "technical",
        sankeyStage: "technical",
        stageLabel: "Technical",
        sourceBucket: "src-referral",
        channel: "referral",
        mode: "hybrid",
        appliedAt: "2026-07-04",
        appliedLabel: "Jul 4",
        fit: 93,
        fitBasis: "screened",
        baseK: 245,
        compMidpointK: 262,
        terminal: false,
        roundsReached: 2,
        needsReview: false,
        needsAction: true,
        stale: false,
        ghosted: false,
        missingComp: false,
        highFit: true,
        interviewPath: true,
        actionState: "interview",
        workstream: "interview",
        healthBadge: { rating: "risky", label: "Risky", title: "Recent funding signal is mixed" },
        action: { cta: "Prep", dueText: "Today" },
        searchText: "vector loom staff ai engineer nyc hybrid referral",
        drawer: {
          floor: 225,
          ask: 260,
          marketLo: 230,
          marketP50: 248,
          marketHi: 285,
          compState: "built",
          compStateLabel: "Built from data",
          compBasis: "NYC AI platform roles",
          compConfidence: "high",
          compHasMarket: true,
          compSampleSize: 18,
          compAsOf: "2026-07-08",
        },
      },
      {
        id: "preview-pinnacle",
        source: "application",
        company: "Pinnacle Data",
        role: "Principal AI Product Engineer",
        domain: "pinnacle.example",
        location: "San Francisco / Remote",
        comp: "$260k+",
        compSummary: "$260k+ base",
        stage: "hiring-manager",
        sankeyStage: "hiring-manager",
        stageLabel: "Hiring Manager",
        sourceBucket: "src-referral",
        channel: "referral",
        mode: "remote",
        appliedAt: "2026-07-01",
        appliedLabel: "Jul 1",
        fit: 90,
        fitBasis: "screened",
        baseK: 260,
        compMidpointK: 275,
        terminal: false,
        roundsReached: 3,
        needsReview: false,
        needsAction: false,
        stale: false,
        ghosted: false,
        missingComp: false,
        highFit: true,
        interviewPath: true,
        actionState: "watch",
        workstream: "interview",
        action: { cta: "Wait", dueText: "This week" },
        searchText: "pinnacle data principal ai product engineer remote referral",
      },
      {
        id: "preview-closed",
        source: "application",
        company: "Closed Door",
        role: "AI Systems Engineer",
        domain: "closed.example",
        location: "Remote",
        comp: "$205k base",
        compSummary: "$205k base",
        stage: "rejected",
        sankeyStage: "screen",
        stageLabel: "Rejected",
        sourceBucket: "src-cold",
        channel: "portal",
        mode: "remote",
        appliedAt: "2026-06-02",
        appliedLabel: "Jun 2",
        fit: 64,
        fitBasis: "screened",
        baseK: 205,
        compMidpointK: 205,
        terminal: true,
        roundsReached: 1,
        needsReview: false,
        needsAction: false,
        stale: false,
        ghosted: false,
        missingComp: false,
        highFit: false,
        interviewPath: false,
        actionState: "archived",
        workstream: "archived",
        action: { cta: "Closed", dueText: "Done" },
        searchText: "closed door ai systems engineer remote portal",
      },
      {
        id: "preview-meridian",
        source: "sourced",
        company: "Meridian Labs",
        role: "Forward Deployed AI Engineer",
        domain: "meridian.example",
        location: "Remote US",
        comp: "$230k-$260k",
        compSummary: "$230k-$260k base",
        stage: "sourced",
        stageLabel: "Review",
        sourceBucket: "src-cold",
        channel: "board",
        mode: "remote",
        fit: 91,
        fitBasis: "triage estimate",
        baseK: 230,
        compMidpointK: 245,
        terminal: false,
        roundsReached: 0,
        needsReview: true,
        needsAction: false,
        stale: false,
        ghosted: false,
        missingComp: false,
        highFit: true,
        interviewPath: false,
        actionState: "review",
        workstream: "review",
        action: { cta: "Evaluate", dueText: "Fresh" },
        searchText: "meridian labs forward deployed ai engineer remote board",
      },
      {
        id: "preview-cobalt",
        source: "sourced",
        company: "Cobalt Works",
        role: "AI Workflow Engineer",
        domain: "cobalt.example",
        location: "New York",
        comp: "$215k-$245k",
        compSummary: "$215k-$245k base",
        stage: "sourced",
        stageLabel: "Review",
        sourceBucket: "src-cold",
        channel: "board",
        mode: "hybrid",
        fit: 86,
        fitBasis: "triage estimate",
        baseK: 215,
        compMidpointK: 230,
        terminal: false,
        roundsReached: 0,
        needsReview: true,
        needsAction: false,
        stale: false,
        ghosted: false,
        missingComp: false,
        highFit: true,
        interviewPath: false,
        actionState: "review",
        workstream: "review",
        action: { cta: "Evaluate", dueText: "Fresh" },
        searchText: "cobalt works ai workflow engineer new york board",
      },
      {
        id: "preview-nova",
        source: "sourced",
        company: "Nova Ledger",
        role: "Applied AI Backend Engineer",
        domain: "nova.example",
        location: "Remote",
        comp: "",
        compSummary: "No comp posted",
        stage: "sourced",
        stageLabel: "Review",
        sourceBucket: "src-recruiter",
        channel: "recruiter",
        mode: "remote",
        fit: 81,
        fitBasis: "triage estimate",
        baseK: null,
        compMidpointK: null,
        terminal: false,
        roundsReached: 0,
        needsReview: true,
        needsAction: false,
        stale: false,
        ghosted: false,
        missingComp: true,
        highFit: true,
        interviewPath: false,
        actionState: "missing-comp",
        workstream: "review",
        action: { cta: "Find comp", dueText: "Fresh" },
        searchText: "nova ledger applied ai backend engineer remote recruiter",
      },
      {
        id: "preview-orbit",
        source: "sourced",
        company: "Orbit Stack",
        role: "LLM Platform Engineer",
        domain: "orbit.example",
        location: "Austin hybrid",
        comp: "$200k-$225k",
        compSummary: "$200k-$225k base",
        stage: "sourced",
        stageLabel: "Hold",
        sourceBucket: "src-referral",
        channel: "referral",
        mode: "hybrid",
        fit: 72,
        fitBasis: "triage estimate",
        baseK: 200,
        compMidpointK: 212,
        terminal: false,
        roundsReached: 0,
        needsReview: true,
        needsAction: false,
        stale: true,
        ghosted: false,
        missingComp: false,
        highFit: false,
        interviewPath: false,
        decayState: "stale",
        actionState: "review",
        workstream: "review",
        action: { cta: "Park", dueText: "5d old" },
        searchText: "orbit stack llm platform engineer austin hybrid referral",
      },
    ],
  },
};
