#!/usr/bin/env bash
# Generate the body of CodesWhat/homebrew-tap's Casks/careerrat.rb.
#
# Prints the cask to stdout by default; pass --write <path> to write it to a
# file instead (this repo's own tree only, never the tap checkout). Version
# comes from package.json unless --version overrides it. sha256 is computed
# from a real DMG: pass --dmg <path> to hash a local build (needed before a
# release is public), or the script downloads the published release DMG for
# the resolved version and hashes that.
#
# The tap PR itself is still opened by hand, see docs/RELEASE.md's
# "Updating the Homebrew Cask" section. This only replaces the hand-edited
# version/sha256 steps, closing the "no cask generator" gap recorded at
# docs/ROADMAP.md:315-318.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

usage() {
	echo "Usage: $0 [--version X.Y.Z] [--dmg /path/to.dmg] [--write /path/to/careerrat.rb]" >&2
	exit 64
}

VERSION=""
DMG_PATH=""
WRITE_PATH=""

while [ $# -gt 0 ]; do
	case "$1" in
	--version)
		VERSION="${2:-}"
		[ -n "$VERSION" ] || usage
		shift 2
		;;
	--dmg)
		DMG_PATH="${2:-}"
		[ -n "$DMG_PATH" ] || usage
		shift 2
		;;
	--write)
		WRITE_PATH="${2:-}"
		[ -n "$WRITE_PATH" ] || usage
		shift 2
		;;
	-h | --help)
		usage
		;;
	*)
		usage
		;;
	esac
done

if [ -z "$VERSION" ]; then
	VERSION="$(node -p "require('$REPO_ROOT/package.json').version")"
fi

TMP_DIR=""
cleanup() {
	[ -z "$TMP_DIR" ] || rm -rf "$TMP_DIR"
}
trap cleanup EXIT

if [ -z "$DMG_PATH" ]; then
	DMG_NAME="CareerRat-$VERSION-arm64.dmg"
	DMG_URL="https://github.com/CodesWhat/careerrat/releases/download/v$VERSION/$DMG_NAME"
	TMP_DIR="$(mktemp -d)"
	DMG_PATH="$TMP_DIR/$DMG_NAME"
	echo "Downloading $DMG_URL ..." >&2
	curl -fsSL -o "$DMG_PATH" "$DMG_URL"
fi

[ -f "$DMG_PATH" ] || {
	echo "error: DMG not found at $DMG_PATH" >&2
	exit 1
}

SHA256="$(shasum -a 256 "$DMG_PATH" | awk '{print $1}')"

emit_cask() {
	cat <<EOF
# This file was generated by scripts/generate-homebrew-cask.sh. The tap PR
# is still opened by hand, see docs/RELEASE.md's "Updating the Homebrew
# Cask" section.
cask "careerrat" do
  version "$VERSION"
  sha256 "$SHA256"

  url "https://github.com/CodesWhat/careerrat/releases/download/v#{version}/CareerRat-#{version}-arm64.dmg"
  name "CareerRat"
  desc "Local, offline-first job-search workspace"
  homepage "https://careerrat.com/"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on arch: :arm64
  # Matches LSMinimumSystemVersion baked into the app by electron-builder.
  depends_on macos: :monterey

  app "CareerRat.app"

  uninstall quit: "com.codeswhat.careerrat"

  # The packaged app sets CAREERRAT_HOME to <userData>/data, so the whole job
  # search (tracker, candidate profile, artifacts) lives under the first path
  # here. Only \`brew uninstall --zap\` touches it; a plain uninstall leaves it.
  zap trash: [
    "~/Library/Application Support/CareerRat",
    "~/Library/Preferences/com.codeswhat.careerrat.plist",
  ]

  caveats <<~EOS
    CareerRat is arm64-only today. There is no Intel build.
    This cask installs the desktop app only. The npm CLI is a separate install.
  EOS
end
EOF
}

if [ -n "$WRITE_PATH" ]; then
	emit_cask >"$WRITE_PATH"
	echo "Wrote cask to $WRITE_PATH" >&2
else
	emit_cask
fi
