export const DASHBOARD_PREVIEW = {
  stats: {
    inPlay: 18,
    responseRate: 26,
    interviews: 4,
  },
  focus: {
    kind: "action",
    title: "Prep Juniper Square technical screen",
    company: "Juniper Square",
    role: "Senior Applied AI Engineer",
    dueText: "today",
    tone: "warning",
    detailId: "preview-juniper",
    cta: "Open prep",
  },
  allNextSteps: [
    {
      title: "Prep Juniper Square technical screen",
      company: "Juniper Square",
      supportingText: "Senior Applied AI Engineer",
      actionLabel: "Prep",
      dueText: "today",
      tone: "warning",
      detailId: "preview-juniper",
    },
    {
      title: "Send Ramp follow-up",
      company: "Ramp",
      supportingText: "Applied AI Engineer",
      actionLabel: "Follow up",
      dueText: "today",
      tone: "warning",
      detailId: "preview-ramp",
    },
    {
      title: "Finish Glean packet",
      company: "Glean",
      supportingText: "AI Search Engineer",
      actionLabel: "Deadline",
      dueText: "Fri",
      detailId: "preview-glean",
    },
  ],
  reviewHoldRoles: [
    {
      company: "Hightouch",
      role: "Staff Engineer, AI Productivity",
      fit: 96,
      domain: "hightouch.com",
      detailId: "preview-hightouch",
    },
    {
      company: "LangChain",
      role: "Deployed Engineer",
      fit: 89,
      domain: "langchain.com",
      detailId: "preview-langchain",
    },
    {
      company: "Glean",
      role: "AI Search Engineer",
      fit: 86,
      domain: "glean.com",
      detailId: "preview-glean",
    },
  ],
  latestRoles: [
    {
      company: "Anthropic",
      role: "Applied AI Architect",
      fit: 94,
      status: "high",
      domain: "anthropic.com",
      detailId: "preview-anthropic",
    },
    {
      company: "Ramp",
      role: "Applied AI Engineer",
      fit: 91,
      status: "high",
      domain: "ramp.com",
      detailId: "preview-ramp",
    },
    {
      company: "Stripe",
      role: "AI Product Engineer",
      fit: 88,
      status: "high",
      domain: "stripe.com",
      detailId: "preview-stripe",
    },
  ],
  sourcedRoles: [
    {
      company: "Perplexity",
      role: "Enterprise AI Engineer",
      fit: 84,
      domain: "perplexity.ai",
      detailId: "preview-perplexity",
    },
  ],
  calendar: {
    todayIso: "2026-07-08",
    today: {
      events: [
        {
          id: "preview-prep-anthropic",
          iso: "2026-07-08",
          time: "9:30 AM",
          title: "Prep Anthropic enterprise AI stories",
          kind: "prep",
          label: "Prep",
          detailId: "preview-anthropic",
        },
        {
          id: "preview-interview-juniper",
          iso: "2026-07-08",
          time: "2:00 PM",
          title: "Juniper Square technical screen",
          kind: "interview",
          label: "Interview",
          detailId: "preview-juniper",
        },
        {
          id: "preview-follow-ramp",
          iso: "2026-07-08",
          time: "4:30 PM",
          title: "Send Ramp follow-up",
          kind: "follow-up",
          label: "Follow-Up",
          detailId: "preview-ramp",
        },
      ],
    },
    upcoming: {
      events: [
        {
          id: "preview-interview-juniper",
          iso: "2026-07-08",
          time: "2:00 PM",
          title: "Juniper Square technical screen",
          kind: "interview",
          label: "Interview",
          detailId: "preview-juniper",
        },
        {
          id: "preview-interview-stripe",
          iso: "2026-07-09",
          time: "11:00 AM",
          title: "Stripe hiring manager screen",
          kind: "interview",
          label: "Interview",
          detailId: "preview-stripe",
        },
        {
          id: "preview-deadline-glean",
          iso: "2026-07-10",
          title: "Glean packet deadline",
          kind: "deadline",
          label: "Deadline",
          detailId: "preview-glean",
        },
      ],
    },
  },
  jobs: {
    visibleCount: 18,
    rail: {
      screenPlus: 4,
      fresh: 7,
      highFit: 6,
      manualReview: 3,
      terminal: 12,
      nextDecision: {
        title: "You have 3 high-fit roles",
        summary: "Decide what to do with them now: promote, skip, or park.",
        action: "manual-review",
        hasWork: true,
      },
    },
  },
};
