export const DASHBOARD_PREVIEW = {
  stats: {
    inPlay: 18,
    responseRate: 26,
    interviews: 4,
  },
  focus: {
    kind: "action",
    title: "Prep Cyberdyne Systems technical screen",
    company: "Cyberdyne Systems",
    role: "Senior Applied AI Engineer",
    dueText: "today",
    tone: "warning",
    detailId: "preview-cyberdyne",
    cta: "Open prep",
  },
  allNextSteps: [
    {
      title: "Prep Cyberdyne Systems technical screen",
      company: "Cyberdyne Systems",
      supportingText: "Senior Applied AI Engineer",
      actionLabel: "Prep",
      dueText: "today",
      tone: "warning",
      detailId: "preview-cyberdyne",
    },
    {
      title: "Send Abstergo Industries follow-up",
      company: "Abstergo Industries",
      supportingText: "Applied AI Engineer",
      actionLabel: "Follow up",
      dueText: "today",
      tone: "warning",
      detailId: "preview-abstergo",
    },
    {
      title: "Finish Globex packet",
      company: "Globex",
      supportingText: "AI Search Engineer",
      actionLabel: "Deadline",
      dueText: "Fri",
      detailId: "preview-piedpiper",
    },
  ],
  reviewHoldRoles: [
    {
      company: "Rekall",
      role: "Staff Engineer, AI Productivity",
      fit: 96,
      domain: "rekall.com",
      detailId: "preview-veridian",
    },
    {
      company: "Encom",
      role: "Deployed Engineer",
      fit: 89,
      domain: "encom.com",
      detailId: "preview-encom",
    },
    {
      company: "Globex",
      role: "AI Search Engineer",
      fit: 86,
      domain: "globex.com",
      detailId: "preview-piedpiper",
    },
  ],
  latestRoles: [
    {
      company: "Tyrell Corporation",
      role: "Applied AI Architect",
      fit: 94,
      status: "high",
      domain: "tyrellcorp.com",
      detailId: "preview-tyrell",
    },
    {
      company: "Abstergo Industries",
      role: "Applied AI Engineer",
      fit: 91,
      status: "high",
      domain: "abstergo.com",
      detailId: "preview-abstergo",
    },
    {
      company: "Massive Dynamic",
      role: "AI Product Engineer",
      fit: 88,
      status: "high",
      domain: "massivedynamic.com",
      detailId: "preview-massivedynamic",
    },
  ],
  sourcedRoles: [
    {
      company: "Hooli",
      role: "Enterprise AI Engineer",
      fit: 84,
      domain: "hooli.com",
      detailId: "preview-hooli",
    },
  ],
  calendar: {
    todayIso: "2026-07-08",
    today: {
      events: [
        {
          id: "preview-prep-tyrell",
          iso: "2026-07-08",
          time: "9:30 AM",
          title: "Prep Tyrell Corporation enterprise AI stories",
          kind: "prep",
          label: "Prep",
          detailId: "preview-tyrell",
        },
        {
          id: "preview-interview-cyberdyne",
          iso: "2026-07-08",
          time: "2:00 PM",
          title: "Cyberdyne Systems technical screen",
          kind: "interview",
          label: "Interview",
          detailId: "preview-cyberdyne",
        },
        {
          id: "preview-follow-abstergo",
          iso: "2026-07-08",
          time: "4:30 PM",
          title: "Send Abstergo Industries follow-up",
          kind: "follow-up",
          label: "Follow-Up",
          detailId: "preview-abstergo",
        },
      ],
    },
    upcoming: {
      events: [
        {
          id: "preview-interview-cyberdyne",
          iso: "2026-07-08",
          time: "2:00 PM",
          title: "Cyberdyne Systems technical screen",
          kind: "interview",
          label: "Interview",
          detailId: "preview-cyberdyne",
        },
        {
          id: "preview-interview-massivedynamic",
          iso: "2026-07-09",
          time: "11:00 AM",
          title: "Massive Dynamic hiring manager screen",
          kind: "interview",
          label: "Interview",
          detailId: "preview-massivedynamic",
        },
        {
          id: "preview-deadline-piedpiper",
          iso: "2026-07-10",
          title: "Globex packet deadline",
          kind: "deadline",
          label: "Deadline",
          detailId: "preview-piedpiper",
        },
      ],
    },
  },
  jobs: {
    visibleCount: 18,
    rail: {
      screenPlus: 4,
      fresh: 7,
      highFit: 6,
      manualReview: 3,
      terminal: 12,
      nextDecision: {
        title: "You have 3 high-fit roles",
        summary: "Decide what to do with them now: promote, skip, or park.",
        action: "manual-review",
        hasWork: true,
      },
    },
  },
};
